apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: modeltraining
  namespace: knative-functions
spec:
  template:
    spec:
      containers:
      - name: modeltraining
        image: docker.io/andersonandrei/functionbench-knative:modeltraining
        resources:  
          requests:
            cpu: 1
            memory: 1024M
          limits:
            cpu: 1
            memory: 1024M